version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root         # Usuario root habilitado
      MYSQL_DATABASE: mnpe             # Base de datos por defecto
    ports:
      - "3307:3306"                     # Evita conflictos con MySQL del sistema
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mmpe
    volumes:
      - .:/docker_tesis_python
    command: uvicorn docker_tesis_python.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
