version: "3.7"

services:
  api:
    build: .
    container_name: fastapi_modbus_api
    ports:
      - "8000:8000"
    volumes:
      - ./docker_tesis_python:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: mnpe
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
